-- Tani Phase 7 — Monetization
-- No commission/price is enabled by default. Admin configures plans and fee rules explicitly.

alter table if exists public.featured_placements
  add column if not exists is_sponsored boolean not null default false,
  add column if not exists sponsored_label text not null default 'ممول',
  add column if not exists request_id uuid,
  add column if not exists priority integer not null default 0;

create table if not exists public.subscription_plans(
 id uuid primary key default gen_random_uuid(),name text not null,description text not null default '',price numeric(14,2) not null default 0 check(price>=0),duration_days integer not null check(duration_days>0),features jsonb not null default '{}'::jsonb,is_active boolean not null default true,created_at timestamptz not null default now(),slug text,audience text not null default 'merchant' check(audience in ('merchant','customer','all')),sort_order integer not null default 0,updated_at timestamptz not null default now());
create unique index if not exists subscription_plans_slug_uidx on public.subscription_plans(slug) where slug is not null;
alter table public.subscription_plans enable row level security;
drop policy if exists tani_subscription_plans_public_read on public.subscription_plans;create policy tani_subscription_plans_public_read on public.subscription_plans for select to anon,authenticated using(is_active);
drop policy if exists tani_subscription_plans_admin_all on public.subscription_plans;create policy tani_subscription_plans_admin_all on public.subscription_plans for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

create table if not exists public.subscriptions(
 id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,plan_id uuid not null references public.subscription_plans(id) on delete restrict,status text not null default 'active' check(status in ('pending','active','past_due','cancelled','expired')),starts_at timestamptz not null default now(),ends_at timestamptz,created_at timestamptz not null default now(),seller_id uuid references public.sellers(id) on delete cascade,source text not null default 'admin',auto_renew boolean not null default false,cancelled_at timestamptz,updated_at timestamptz not null default now());
create index if not exists subscriptions_user_status_idx on public.subscriptions(user_id,status,ends_at);create index if not exists subscriptions_seller_status_idx on public.subscriptions(seller_id,status,ends_at);create index if not exists subscriptions_plan_idx on public.subscriptions(plan_id);
alter table public.subscriptions enable row level security;drop policy if exists tani_subscriptions_owner_read on public.subscriptions;create policy tani_subscriptions_owner_read on public.subscriptions for select to authenticated using(user_id=(select auth.uid()) or public.current_user_role()=any(array['admin','support']));drop policy if exists tani_subscriptions_admin_all on public.subscriptions;create policy tani_subscriptions_admin_all on public.subscriptions for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

create table if not exists public.subscription_requests(
 id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,seller_id uuid not null references public.sellers(id) on delete cascade,plan_id uuid not null references public.subscription_plans(id) on delete restrict,status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled')),note text,admin_note text,created_at timestamptz not null default now(),reviewed_at timestamptz,reviewed_by uuid references auth.users(id) on delete set null);
create unique index if not exists subscription_requests_one_pending_uidx on public.subscription_requests(seller_id) where status='pending';create index if not exists subscription_requests_status_idx on public.subscription_requests(status,created_at desc);create index if not exists subscription_requests_user_idx on public.subscription_requests(user_id);create index if not exists subscription_requests_plan_idx on public.subscription_requests(plan_id);
alter table public.subscription_requests enable row level security;drop policy if exists tani_subscription_requests_owner_read on public.subscription_requests;create policy tani_subscription_requests_owner_read on public.subscription_requests for select to authenticated using(user_id=(select auth.uid()) or public.current_user_role()=any(array['admin','support']));drop policy if exists tani_subscription_requests_owner_insert on public.subscription_requests;create policy tani_subscription_requests_owner_insert on public.subscription_requests for insert to authenticated with check(user_id=(select auth.uid()) and status='pending' and exists(select 1 from public.sellers s where s.id=subscription_requests.seller_id and s.user_id=(select auth.uid()) and s.verification_status='approved') and exists(select 1 from public.subscription_plans p where p.id=subscription_requests.plan_id and p.is_active and p.audience in ('merchant','all')));drop policy if exists tani_subscription_requests_owner_cancel on public.subscription_requests;create policy tani_subscription_requests_owner_cancel on public.subscription_requests for update to authenticated using(user_id=(select auth.uid()) and status='pending') with check(user_id=(select auth.uid()) and status='cancelled');drop policy if exists tani_subscription_requests_admin_update on public.subscription_requests;create policy tani_subscription_requests_admin_update on public.subscription_requests for update to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

create or replace function public.my_merchant_entitlements() returns jsonb language sql stable security invoker set search_path=public,pg_temp as $$select coalesce(jsonb_object_agg(k,v),'{}'::jsonb) from(select e.key k,e.value v from public.subscriptions s join public.subscription_plans p on p.id=s.plan_id and p.is_active cross join lateral jsonb_each(p.features)e where s.user_id=(select auth.uid()) and s.status='active' and s.starts_at<=now() and(s.ends_at is null or s.ends_at>now()) and(s.seller_id is null or exists(select 1 from public.sellers x where x.id=s.seller_id and x.user_id=(select auth.uid()))))q$$;revoke all on function public.my_merchant_entitlements() from public,anon;grant execute on function public.my_merchant_entitlements() to authenticated;

create table if not exists public.fee_rules(
 id uuid primary key default gen_random_uuid(),code text not null unique,context text not null check(context in ('order','merchant_subscription','featured_placement','advertising')),percentage numeric(7,4) not null default 0 check(percentage between 0 and 100),fixed_amount numeric(14,2) not null default 0 check(fixed_amount>=0),min_amount numeric(14,2),max_fee numeric(14,2),is_active boolean not null default false,starts_at timestamptz,ends_at timestamptz,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.fee_rules enable row level security;drop policy if exists tani_fee_rules_public_read on public.fee_rules;create policy tani_fee_rules_public_read on public.fee_rules for select to anon,authenticated using(is_active and(starts_at is null or starts_at<=now()) and(ends_at is null or ends_at>now()));drop policy if exists tani_fee_rules_admin_all on public.fee_rules;create policy tani_fee_rules_admin_all on public.fee_rules for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');
create or replace function public.fee_quote(p_context text,p_amount numeric) returns jsonb language sql stable security invoker set search_path=public,pg_temp as $$with matched as(select * from public.fee_rules where context=p_context and is_active and(starts_at is null or starts_at<=now()) and(ends_at is null or ends_at>now()) and(min_amount is null or p_amount>=min_amount) order by starts_at desc nulls last,created_at desc limit 1),calc as(select code,least(coalesce(max_fee,1e18::numeric),round(greatest(p_amount,0)*percentage/100+fixed_amount,2))fee from matched)select jsonb_build_object('context',p_context,'base_amount',greatest(p_amount,0),'fee',coalesce((select fee from calc),0),'rule_code',(select code from calc))$$;grant execute on function public.fee_quote(text,numeric) to anon,authenticated;

create table if not exists public.featured_requests(
 id uuid primary key default gen_random_uuid(),seller_id uuid not null references public.sellers(id) on delete cascade,product_id uuid references public.products(id) on delete cascade,placement text not null,requested_starts_at timestamptz,requested_ends_at timestamptz,status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled','expired')),merchant_note text,admin_note text,created_at timestamptz not null default now(),reviewed_at timestamptz,reviewed_by uuid references auth.users(id) on delete set null);
create index if not exists featured_requests_seller_status_idx on public.featured_requests(seller_id,status,created_at desc);create index if not exists featured_requests_product_idx on public.featured_requests(product_id);alter table public.featured_requests enable row level security;drop policy if exists tani_featured_requests_owner_read on public.featured_requests;create policy tani_featured_requests_owner_read on public.featured_requests for select to authenticated using(exists(select 1 from public.sellers s where s.id=featured_requests.seller_id and s.user_id=(select auth.uid())) or public.current_user_role()=any(array['admin','support']));drop policy if exists tani_featured_requests_owner_insert on public.featured_requests;create policy tani_featured_requests_owner_insert on public.featured_requests for insert to authenticated with check(status='pending' and exists(select 1 from public.sellers s where s.id=featured_requests.seller_id and s.user_id=(select auth.uid()) and s.verification_status='approved') and(product_id is null or exists(select 1 from public.products p where p.id=featured_requests.product_id and p.seller_id=featured_requests.seller_id)));drop policy if exists tani_featured_requests_owner_cancel on public.featured_requests;create policy tani_featured_requests_owner_cancel on public.featured_requests for update to authenticated using(status='pending' and exists(select 1 from public.sellers s where s.id=featured_requests.seller_id and s.user_id=(select auth.uid()))) with check(status='cancelled' and exists(select 1 from public.sellers s where s.id=featured_requests.seller_id and s.user_id=(select auth.uid())));drop policy if exists tani_featured_requests_admin_update on public.featured_requests;create policy tani_featured_requests_admin_update on public.featured_requests for update to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

do $$ begin alter table public.featured_placements add constraint featured_placements_request_id_fkey foreign key(request_id) references public.featured_requests(id) on delete set null;exception when duplicate_object then null;end $$;
create index if not exists featured_placements_product_idx on public.featured_placements(product_id);create index if not exists featured_placements_seller_idx on public.featured_placements(seller_id);create index if not exists featured_placements_request_idx on public.featured_placements(request_id);

create table if not exists public.merchant_ad_campaigns(
 id uuid primary key default gen_random_uuid(),seller_id uuid not null references public.sellers(id) on delete cascade,name text not null,placement text not null,product_id uuid references public.products(id) on delete cascade,budget numeric(14,2) check(budget is null or budget>=0),starts_at timestamptz,ends_at timestamptz,status text not null default 'draft' check(status in ('draft','pending','active','paused','ended','rejected')),impressions bigint not null default 0,clicks bigint not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());create index if not exists merchant_ad_campaigns_seller_status_idx on public.merchant_ad_campaigns(seller_id,status,created_at desc);create index if not exists merchant_ad_campaigns_product_idx on public.merchant_ad_campaigns(product_id);alter table public.merchant_ad_campaigns enable row level security;drop policy if exists tani_ad_campaigns_owner_read on public.merchant_ad_campaigns;create policy tani_ad_campaigns_owner_read on public.merchant_ad_campaigns for select to authenticated using(exists(select 1 from public.sellers s where s.id=merchant_ad_campaigns.seller_id and s.user_id=(select auth.uid())) or public.current_user_role()=any(array['admin','support']));drop policy if exists tani_ad_campaigns_owner_insert on public.merchant_ad_campaigns;create policy tani_ad_campaigns_owner_insert on public.merchant_ad_campaigns for insert to authenticated with check(status in ('draft','pending') and exists(select 1 from public.sellers s where s.id=merchant_ad_campaigns.seller_id and s.user_id=(select auth.uid()) and s.verification_status='approved'));drop policy if exists tani_ad_campaigns_admin_update on public.merchant_ad_campaigns;create policy tani_ad_campaigns_admin_update on public.merchant_ad_campaigns for update to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

create table if not exists public.payment_methods(code text primary key,display_name text not null,provider text,is_online boolean not null default false,is_active boolean not null default false,sort_order integer not null default 0,public_config jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());insert into public.payment_methods(code,display_name,provider,is_online,is_active,sort_order) values('cod','الدفع عند الاستلام',null,false,true,0) on conflict(code) do update set display_name=excluded.display_name,is_active=true;alter table public.payment_methods enable row level security;drop policy if exists tani_payment_methods_public_read on public.payment_methods;create policy tani_payment_methods_public_read on public.payment_methods for select to anon,authenticated using(is_active);drop policy if exists tani_payment_methods_admin_all on public.payment_methods;create policy tani_payment_methods_admin_all on public.payment_methods for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

create table if not exists public.billing_transactions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,seller_id uuid references public.sellers(id) on delete set null,purpose text not null check(purpose in ('subscription','featured_placement','advertising','service_fee')),reference_id uuid,amount numeric(14,2) not null check(amount>=0),currency text not null default 'SDG',payment_method text not null references public.payment_methods(code),provider text,provider_reference text,status text not null default 'pending' check(status in ('pending','authorized','paid','failed','cancelled','refunded')),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());create index if not exists billing_transactions_user_idx on public.billing_transactions(user_id,created_at desc);create index if not exists billing_transactions_seller_idx on public.billing_transactions(seller_id,created_at desc);alter table public.billing_transactions enable row level security;drop policy if exists tani_billing_owner_read on public.billing_transactions;create policy tani_billing_owner_read on public.billing_transactions for select to authenticated using(user_id=(select auth.uid()) or public.current_user_role()=any(array['admin','support']));drop policy if exists tani_billing_admin_all on public.billing_transactions;create policy tani_billing_admin_all on public.billing_transactions for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

create or replace function public.admin_review_subscription_request(p_request_id uuid,p_status text,p_note text default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$declare v_req public.subscription_requests%rowtype;v_plan public.subscription_plans%rowtype;v_subscription_id uuid;begin if public.current_user_role()<>'admin' then raise exception 'admin required';end if;if p_status not in('approved','rejected') then raise exception 'invalid status';end if;select * into v_req from public.subscription_requests where id=p_request_id for update;if v_req.id is null or v_req.status<>'pending' then raise exception 'request not available';end if;select * into v_plan from public.subscription_plans where id=v_req.plan_id and is_active;if v_plan.id is null then raise exception 'plan not available';end if;if p_status='approved' then update public.subscriptions set status='expired',updated_at=now() where seller_id=v_req.seller_id and status='active';insert into public.subscriptions(user_id,seller_id,plan_id,status,starts_at,ends_at,source,auto_renew) values(v_req.user_id,v_req.seller_id,v_req.plan_id,'active',now(),now()+make_interval(days=>v_plan.duration_days),'admin',false) returning id into v_subscription_id;end if;update public.subscription_requests set status=p_status,admin_note=p_note,reviewed_at=now(),reviewed_by=(select auth.uid()) where id=p_request_id;return v_subscription_id;end $$;revoke all on function public.admin_review_subscription_request(uuid,text,text) from public,anon;grant execute on function public.admin_review_subscription_request(uuid,text,text) to authenticated;

create or replace function public.admin_review_featured_request(p_request_id uuid,p_status text,p_note text default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$declare v_req public.featured_requests%rowtype;v_id uuid;begin if public.current_user_role()<>'admin' then raise exception 'admin required';end if;if p_status not in('approved','rejected') then raise exception 'invalid status';end if;select * into v_req from public.featured_requests where id=p_request_id for update;if v_req.id is null or v_req.status<>'pending' then raise exception 'request not available';end if;if p_status='approved' then insert into public.featured_placements(product_id,seller_id,placement,starts_at,ends_at,is_active,is_sponsored,sponsored_label,request_id,priority) values(v_req.product_id,v_req.seller_id,v_req.placement,coalesce(v_req.requested_starts_at,now()),v_req.requested_ends_at,true,true,'ممول',v_req.id,0) returning id into v_id;end if;update public.featured_requests set status=p_status,admin_note=p_note,reviewed_at=now(),reviewed_by=(select auth.uid()) where id=p_request_id;return v_id;end $$;revoke all on function public.admin_review_featured_request(uuid,text,text) from public,anon;grant execute on function public.admin_review_featured_request(uuid,text,text) to authenticated;

grant select on public.subscription_plans to anon,authenticated;grant insert,update,delete on public.subscription_plans to authenticated;grant select,insert,update,delete on public.subscriptions to authenticated;grant select,insert,update on public.subscription_requests to authenticated;grant select,insert,update,delete on public.fee_rules to authenticated;grant select on public.fee_rules to anon;grant select,insert,update on public.featured_requests to authenticated;grant select,insert,update on public.merchant_ad_campaigns to authenticated;grant select on public.payment_methods to anon,authenticated;grant insert,update,delete on public.payment_methods to authenticated;grant select,insert,update,delete on public.billing_transactions to authenticated;
