-- Tani Phase 6 — Growth: favorites, inbox notifications, referrals, banners and merchant metrics.
create schema if not exists private;
revoke all on schema private from public;

create table if not exists public.favorites(
 id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,product_id uuid not null references public.products(id) on delete cascade,created_at timestamptz not null default now(),unique(user_id,product_id));
alter table public.favorites enable row level security;create index if not exists favorites_user_created_idx on public.favorites(user_id,created_at desc);create index if not exists favorites_product_idx on public.favorites(product_id);
drop policy if exists tani_favorites_owner_read on public.favorites;create policy tani_favorites_owner_read on public.favorites for select to authenticated using(user_id=(select auth.uid()));
drop policy if exists tani_favorites_owner_insert on public.favorites;create policy tani_favorites_owner_insert on public.favorites for insert to authenticated with check(user_id=(select auth.uid()));
drop policy if exists tani_favorites_owner_delete on public.favorites;create policy tani_favorites_owner_delete on public.favorites for delete to authenticated using(user_id=(select auth.uid()));

create table if not exists public.notifications(
 id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,type text not null,title text not null,body text not null,data jsonb not null default '{}'::jsonb,read_at timestamptz,created_at timestamptz not null default now());
alter table public.notifications add column if not exists dedupe_key text;create unique index if not exists notifications_user_dedupe_idx on public.notifications(user_id,dedupe_key) where dedupe_key is not null;create index if not exists notifications_user_id_idx on public.notifications(user_id,created_at desc);
alter table public.notifications enable row level security;drop policy if exists tani_notifications_owner_read on public.notifications;create policy tani_notifications_owner_read on public.notifications for select to authenticated using(user_id=(select auth.uid()));drop policy if exists tani_notifications_owner_update on public.notifications;create policy tani_notifications_owner_update on public.notifications for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));

create table if not exists public.notification_preferences(user_id uuid primary key references auth.users(id) on delete cascade,push_enabled boolean not null default true,order_updates boolean not null default true,promotions boolean not null default true,messages boolean not null default true,updated_at timestamptz not null default now());
alter table public.notification_preferences enable row level security;drop policy if exists tani_notification_preferences_owner_read on public.notification_preferences;create policy tani_notification_preferences_owner_read on public.notification_preferences for select to authenticated using(user_id=(select auth.uid()));drop policy if exists tani_notification_preferences_owner_insert on public.notification_preferences;create policy tani_notification_preferences_owner_insert on public.notification_preferences for insert to authenticated with check(user_id=(select auth.uid()));drop policy if exists tani_notification_preferences_owner_update on public.notification_preferences;create policy tani_notification_preferences_owner_update on public.notification_preferences for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));

create table if not exists public.referral_codes(user_id uuid primary key references auth.users(id) on delete cascade,code text not null unique check(char_length(code) between 6 and 32),created_at timestamptz not null default now());alter table public.referral_codes enable row level security;drop policy if exists tani_referral_codes_owner_read on public.referral_codes;create policy tani_referral_codes_owner_read on public.referral_codes for select to authenticated using(user_id=(select auth.uid()));drop policy if exists tani_referral_codes_owner_insert on public.referral_codes;create policy tani_referral_codes_owner_insert on public.referral_codes for insert to authenticated with check(user_id=(select auth.uid()));
create table if not exists public.referrals(id uuid primary key default gen_random_uuid(),referrer_id uuid not null references auth.users(id) on delete cascade,referred_id uuid not null references auth.users(id) on delete cascade,code text,status text not null default 'pending' check(status in ('pending','completed','cancelled')),created_at timestamptz not null default now(),unique(referred_id));alter table public.referrals enable row level security;create index if not exists referrals_referrer_idx on public.referrals(referrer_id,created_at desc);drop policy if exists tani_referrals_participant_read on public.referrals;create policy tani_referrals_participant_read on public.referrals for select to authenticated using(referrer_id=(select auth.uid()) or referred_id=(select auth.uid()));
create or replace function public.my_referral_code() returns text language plpgsql security invoker set search_path=public,pg_temp as $$declare v_uid uuid:=(select auth.uid());v_code text;begin if v_uid is null then raise exception 'authentication required';end if;select code into v_code from public.referral_codes where user_id=v_uid;if v_code is null then v_code:='TANI-'||upper(substr(md5(v_uid::text),1,10));insert into public.referral_codes(user_id,code) values(v_uid,v_code) on conflict(user_id) do update set code=referral_codes.code returning code into v_code;end if;return v_code;end $$;revoke all on function public.my_referral_code() from public,anon;grant execute on function public.my_referral_code() to authenticated;
create or replace function public.apply_referral_code(p_code text) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$declare v_uid uuid:=(select auth.uid());v_referrer uuid;v_code text:=upper(trim(p_code));begin if v_uid is null then raise exception 'authentication required';end if;select user_id into v_referrer from public.referral_codes where upper(code)=v_code;if v_referrer is null then raise exception 'invalid referral code';end if;if v_referrer=v_uid then raise exception 'cannot refer yourself';end if;if exists(select 1 from public.referrals where referred_id=v_uid) then return false;end if;insert into public.referrals(referrer_id,referred_id,code,status) values(v_referrer,v_uid,v_code,'pending');return true;end $$;revoke all on function public.apply_referral_code(text) from public,anon;grant execute on function public.apply_referral_code(text) to authenticated;

create table if not exists public.banners(id uuid primary key default gen_random_uuid(),title text not null,image_url text not null,action_type text,action_value text,starts_at timestamptz,ends_at timestamptz,sort_order integer not null default 0,is_active boolean not null default true,created_at timestamptz not null default now());alter table public.banners enable row level security;drop policy if exists tani_banners_public_read on public.banners;create policy tani_banners_public_read on public.banners for select to anon,authenticated using(is_active and (starts_at is null or starts_at<=now()) and (ends_at is null or ends_at>=now()));drop policy if exists tani_banners_admin_write on public.banners;create policy tani_banners_admin_write on public.banners for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');
create table if not exists public.campaigns(id uuid primary key default gen_random_uuid(),name text not null,description text not null default '',starts_at timestamptz,ends_at timestamptz,status text not null default 'draft',created_at timestamptz not null default now());alter table public.campaigns enable row level security;drop policy if exists tani_campaigns_admin_all on public.campaigns;create policy tani_campaigns_admin_all on public.campaigns for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

create table if not exists public.merchant_metrics(id uuid primary key default gen_random_uuid(),seller_id uuid not null unique references public.sellers(id) on delete cascade,total_orders integer not null default 0,completed_orders integer not null default 0,cancelled_orders integer not null default 0,total_sales numeric(14,2) not null default 0,average_rating numeric(3,2),updated_at timestamptz not null default now());
alter table public.merchant_metrics add column if not exists product_views integer not null default 0,add column if not exists repeat_customers integer not null default 0,add column if not exists conversion_rate numeric(6,2) not null default 0,add column if not exists cancellation_rate numeric(6,2) not null default 0,add column if not exists avg_response_minutes numeric(10,2);alter table public.merchant_metrics enable row level security;drop policy if exists tani_merchant_metrics_owner_read on public.merchant_metrics;create policy tani_merchant_metrics_owner_read on public.merchant_metrics for select to authenticated using(exists(select 1 from public.sellers s where s.id=merchant_metrics.seller_id and s.user_id=(select auth.uid())) or public.current_user_role()=any(array['admin','support']));

create or replace function private.enqueue_order_notification() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare v_order public.orders%rowtype;v_title text;v_merchant uuid;begin select * into v_order from public.orders where id=new.order_id;if v_order.id is null then return new;end if;v_title:=case new.to_status when 'accepted' then 'تم قبول طلبك' when 'preparing' then 'طلبك قيد التجهيز' when 'ready' then 'طلبك جاهز' when 'out_for_delivery' then 'طلبك خرج للتوصيل' when 'delivered' then 'تم تسليم طلبك' when 'cancelled' then 'تم إلغاء الطلب' when 'rejected' then 'تعذر قبول الطلب' else 'تحديث على طلبك' end;insert into public.notifications(user_id,type,title,body,data,dedupe_key) values(v_order.customer_id,'order_update',v_title,coalesce(v_order.store_name_snapshot,'المتجر')||' — '||v_title,jsonb_build_object('order_id',v_order.id,'order_group_id',v_order.order_group_id,'status',new.to_status),'order:'||v_order.id||':'||new.to_status) on conflict(user_id,dedupe_key) where dedupe_key is not null do nothing;select user_id into v_merchant from public.sellers where id=v_order.seller_id;if v_merchant is not null and v_merchant<>v_order.customer_id then insert into public.notifications(user_id,type,title,body,data,dedupe_key) values(v_merchant,'merchant_order_update','تحديث طلب','حالة الطلب أصبحت: '||new.to_status,jsonb_build_object('order_id',v_order.id,'status',new.to_status),'merchant_order:'||v_order.id||':'||new.to_status) on conflict(user_id,dedupe_key) where dedupe_key is not null do nothing;end if;return new;end $$;revoke all on function private.enqueue_order_notification() from public,anon,authenticated;drop trigger if exists tani_order_status_notifications on public.order_status_history;create trigger tani_order_status_notifications after insert on public.order_status_history for each row execute function private.enqueue_order_notification();
create or replace function private.enqueue_new_order_notification() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare v_uid uuid;begin select user_id into v_uid from public.sellers where id=new.seller_id;if v_uid is not null then insert into public.notifications(user_id,type,title,body,data,dedupe_key) values(v_uid,'new_order','طلب جديد','وصلك طلب جديد على تاني',jsonb_build_object('order_id',new.id,'order_group_id',new.order_group_id),'new_order:'||new.id) on conflict(user_id,dedupe_key) where dedupe_key is not null do nothing;end if;return new;end $$;revoke all on function private.enqueue_new_order_notification() from public,anon,authenticated;drop trigger if exists tani_new_order_notification on public.orders;create trigger tani_new_order_notification after insert on public.orders for each row execute function private.enqueue_new_order_notification();
create or replace function private.enqueue_merchant_verification_notification() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin if old.verification_status is distinct from new.verification_status then insert into public.notifications(user_id,type,title,body,data,dedupe_key) values(new.user_id,'merchant_verification','تحديث حساب التاجر',case new.verification_status when 'approved' then 'تم اعتماد متجرك على تاني' when 'changes_requested' then 'طلب التاجر يحتاج تعديلات قبل الاعتماد' when 'rejected' then 'تمت مراجعة طلب التاجر ولم يتم اعتماده' when 'suspended' then 'تم تعليق حساب التاجر مؤقتاً' else 'تم تحديث حالة طلب التاجر' end,jsonb_build_object('merchant_id',new.id,'status',new.verification_status),'merchant_verification:'||new.id||':'||new.verification_status) on conflict(user_id,dedupe_key) where dedupe_key is not null do nothing;end if;return new;end $$;revoke all on function private.enqueue_merchant_verification_notification() from public,anon,authenticated;drop trigger if exists tani_merchant_verification_notification on public.merchant_profiles;create trigger tani_merchant_verification_notification after update of verification_status on public.merchant_profiles for each row execute function private.enqueue_merchant_verification_notification();

create or replace function private.enqueue_stock_alert() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare v_uid uuid;begin if new.stock<=3 and(old.stock is null or old.stock>new.stock) then select user_id into v_uid from public.sellers where id=new.seller_id;if v_uid is not null then insert into public.notifications(user_id,type,title,body,data,dedupe_key) values(v_uid,'stock_alert','تنبيه مخزون',new.name||' — المتبقي '||new.stock,jsonb_build_object('product_id',new.id,'stock',new.stock),'stock:'||new.id||':'||new.stock) on conflict(user_id,dedupe_key) where dedupe_key is not null do nothing;end if;end if;return new;end $$;revoke all on function private.enqueue_stock_alert() from public,anon,authenticated;drop trigger if exists tani_product_stock_alert on public.products;create trigger tani_product_stock_alert after update of stock on public.products for each row execute function private.enqueue_stock_alert();

create or replace function private.complete_referral_after_order() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin if new.status='delivered' and old.status is distinct from new.status then update public.referrals set status='completed' where referred_id=new.customer_id and status='pending';end if;return new;end $$;revoke all on function private.complete_referral_after_order() from public,anon,authenticated;drop trigger if exists tani_complete_referral_order on public.orders;create trigger tani_complete_referral_order after update of status on public.orders for each row execute function private.complete_referral_after_order();

create or replace function private.refresh_merchant_metrics(p_seller_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$declare v_total int:=0;v_completed int:=0;v_cancelled int:=0;v_sales numeric:=0;v_rating numeric:=null;v_views int:=0;v_repeat int:=0;v_conversion numeric:=0;v_cancel numeric:=0;v_response numeric:=null;begin if p_seller_id is null then return;end if;select count(*),count(*) filter(where status='delivered'),count(*) filter(where status in ('cancelled','rejected')),coalesce(sum(total) filter(where status='delivered'),0) into v_total,v_completed,v_cancelled,v_sales from public.orders where seller_id=p_seller_id;if to_regclass('public.merchant_reviews') is not null then select avg(rating) into v_rating from public.merchant_reviews where seller_id=p_seller_id and status='published';end if;select count(*) into v_views from public.app_events e join public.products p on p.id=e.entity_id where e.event_name='product_view' and e.entity_type='product' and p.seller_id=p_seller_id;select count(*) into v_repeat from(select customer_id from public.orders where seller_id=p_seller_id and status='delivered' group by customer_id having count(*)>1)q;if v_views>0 then v_conversion:=round(v_total::numeric/v_views*100,2);end if;if v_total>0 then v_cancel:=round(v_cancelled::numeric/v_total*100,2);end if;insert into public.merchant_metrics(seller_id,total_orders,completed_orders,cancelled_orders,total_sales,average_rating,product_views,repeat_customers,conversion_rate,cancellation_rate,avg_response_minutes,updated_at) values(p_seller_id,v_total,v_completed,v_cancelled,v_sales,v_rating,v_views,v_repeat,v_conversion,v_cancel,v_response,now()) on conflict(seller_id) do update set total_orders=excluded.total_orders,completed_orders=excluded.completed_orders,cancelled_orders=excluded.cancelled_orders,total_sales=excluded.total_sales,average_rating=excluded.average_rating,product_views=excluded.product_views,repeat_customers=excluded.repeat_customers,conversion_rate=excluded.conversion_rate,cancellation_rate=excluded.cancellation_rate,updated_at=now();end $$;revoke all on function private.refresh_merchant_metrics(uuid) from public,anon,authenticated;
create or replace function private.refresh_metrics_from_order() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin perform private.refresh_merchant_metrics(coalesce(new.seller_id,old.seller_id));return coalesce(new,old);end $$;revoke all on function private.refresh_metrics_from_order() from public,anon,authenticated;drop trigger if exists tani_refresh_metrics_order on public.orders;create trigger tani_refresh_metrics_order after insert or delete or update of status on public.orders for each row execute function private.refresh_metrics_from_order();

grant select,insert,delete on public.favorites to authenticated;grant select,update on public.notifications to authenticated;grant select,insert,update on public.notification_preferences to authenticated;grant select,insert on public.referral_codes to authenticated;grant select on public.referrals to authenticated;grant select on public.banners to anon,authenticated;grant insert,update,delete on public.banners to authenticated;grant select,insert,update,delete on public.campaigns to authenticated;grant select on public.merchant_metrics to authenticated;
