create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,name text not null default '' check(char_length(trim(name)) between 2 and 100),phone text not null default '' check(char_length(trim(phone)) between 7 and 30),role text not null default 'customer' check(role in('customer','seller','admin','support')),avatar_url text,is_active boolean not null default true,deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.categories(id uuid primary key default gen_random_uuid(),name text not null unique,image text,created_at timestamptz not null default now());
create table if not exists public.sellers(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references public.profiles(id) on delete cascade,store_name text not null,verification_status text not null default 'pending' check(verification_status in('pending','approved','rejected','suspended')),delivery_fee numeric(12,2) not null default 0 check(delivery_fee>=0),created_at timestamptz not null default now());
create table if not exists public.products(id uuid primary key default gen_random_uuid(),seller_id uuid not null references public.sellers(id) on delete cascade,category_id uuid references public.categories(id) on delete set null,name text not null,description text not null default '',price numeric(12,2) not null check(price>=0),stock integer not null default 0 check(stock>=0),image text,is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),customer_id uuid not null references public.profiles(id) on delete restrict,total numeric(12,2) not null default 0 check(total>=0),delivery_fee numeric(12,2) not null default 0 check(delivery_fee>=0),status text not null default 'pending' check(status in('pending','confirmed','preparing','shipped','delivered','cancelled')),address text not null,phone text not null,created_at timestamptz not null default now());
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid not null references public.products(id) on delete restrict,seller_id uuid not null references public.sellers(id) on delete restrict,quantity integer not null check(quantity>0),unit_price numeric(12,2) not null check(unit_price>=0));
create index if not exists products_active_created_idx on public.products(is_active,created_at desc);create index if not exists products_seller_idx on public.products(seller_id);create index if not exists orders_customer_created_idx on public.orders(customer_id,created_at desc);create index if not exists order_items_seller_idx on public.order_items(seller_id);
create schema if not exists private;revoke all on schema private from public;drop function if exists public.handle_new_user();create or replace function private.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,name,phone,role,created_at,updated_at,is_active) values(new.id,trim(coalesce(new.raw_user_meta_data->>'name','')),trim(coalesce(new.raw_user_meta_data->>'phone','')),'customer',now(),now(),true) on conflict(id) do update set name=excluded.name,phone=excluded.phone,updated_at=now();return new;end; $$;revoke all on function private.handle_new_user() from public;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();

-- Authorization helper required by Phase 1+ policies.
create or replace function public.current_user_role() returns text
language sql stable security definer
set search_path='public','pg_temp' as $$
  select p.role from public.profiles p
  where p.id=auth.uid() and p.is_active=true and p.deleted_at is null
  limit 1
$$;
revoke all on function public.current_user_role() from public;
grant execute on function public.current_user_role() to anon,authenticated;
create or replace function public.place_order(p_address text,p_phone text,p_items jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare v_customer uuid:=auth.uid();v_order uuid;v_total numeric(12,2):=0;v_delivery numeric(12,2):=0;v_seller uuid;v_seller_count int;v_product record;v_item jsonb;v_qty int;
begin if v_customer is null then raise exception 'تسجيل الدخول مطلوب';end if;if coalesce(trim(p_address),'')='' then raise exception 'العنوان مطلوب';end if;if coalesce(trim(p_phone),'')='' then raise exception 'رقم الهاتف مطلوب';end if;if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'السلة فارغة';end if;
select count(distinct p.seller_id),min(p.seller_id) into v_seller_count,v_seller from jsonb_array_elements(p_items)i join public.products p on p.id=(i->>'product_id')::uuid where p.is_active=true;if v_seller_count<>1 then raise exception 'في نسخة MVP يجب أن يكون الطلب من متجر واحد فقط';end if;select delivery_fee into v_delivery from public.sellers where id=v_seller;if v_delivery is null then raise exception 'المتجر غير صالح';end if;
for v_item in select * from jsonb_array_elements(p_items) loop v_qty:=(v_item->>'quantity')::int;if v_qty is null or v_qty<=0 then raise exception 'كمية غير صالحة';end if;select * into v_product from public.products where id=(v_item->>'product_id')::uuid and is_active=true for update;if not found then raise exception 'المنتج غير متاح';end if;if v_product.seller_id<>v_seller then raise exception 'لا يمكن جمع منتجات من متاجر مختلفة في طلب MVP واحد';end if;if v_product.stock<v_qty then raise exception 'المخزون غير كافٍ للمنتج: %',v_product.name;end if;v_total:=v_total+(v_product.price*v_qty);end loop;
insert into public.orders(customer_id,total,delivery_fee,status,address,phone)values(v_customer,v_total+v_delivery,v_delivery,'pending',trim(p_address),trim(p_phone))returning id into v_order;for v_item in select * from jsonb_array_elements(p_items) loop v_qty:=(v_item->>'quantity')::int;select * into v_product from public.products where id=(v_item->>'product_id')::uuid for update;insert into public.order_items(order_id,product_id,seller_id,quantity,unit_price)values(v_order,v_product.id,v_product.seller_id,v_qty,v_product.price);update public.products set stock=stock-v_qty where id=v_product.id;end loop;return v_order;end;$$;
revoke all on function public.place_order(text,text,jsonb) from public;grant execute on function public.place_order(text,text,jsonb) to authenticated;
alter table public.profiles enable row level security;alter table public.categories enable row level security;alter table public.sellers enable row level security;alter table public.products enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;
drop policy if exists profiles_select_own on public.profiles;create policy profiles_select_own on public.profiles for select to authenticated using(id=(select auth.uid()));drop policy if exists profiles_update_own on public.profiles;create policy profiles_update_own on public.profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
drop policy if exists categories_public_select on public.categories;create policy categories_public_select on public.categories for select to anon,authenticated using(true);
drop policy if exists sellers_public_select on public.sellers;create policy sellers_public_select on public.sellers for select to anon,authenticated using(verification_status='approved' or user_id=auth.uid());drop policy if exists sellers_insert_own on public.sellers;create policy sellers_insert_own on public.sellers for insert to authenticated with check(user_id=auth.uid());drop policy if exists sellers_update_own on public.sellers;create policy sellers_update_own on public.sellers for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists products_public_select on public.products;create policy products_public_select on public.products for select to anon,authenticated using(is_active=true or seller_id in(select id from public.sellers where user_id=auth.uid()));drop policy if exists products_insert_approved_seller on public.products;create policy products_insert_approved_seller on public.products for insert to authenticated with check(seller_id in(select id from public.sellers where user_id=auth.uid() and verification_status='approved'));drop policy if exists products_update_own on public.products;create policy products_update_own on public.products for update to authenticated using(seller_id in(select id from public.sellers where user_id=auth.uid())) with check(seller_id in(select id from public.sellers where user_id=auth.uid()));
drop policy if exists orders_select_own on public.orders;create policy orders_select_own on public.orders for select to authenticated using(customer_id=auth.uid());drop policy if exists order_items_select_customer on public.order_items;create policy order_items_select_customer on public.order_items for select to authenticated using(order_id in(select id from public.orders where customer_id=auth.uid()));drop policy if exists order_items_select_seller on public.order_items;create policy order_items_select_seller on public.order_items for select to authenticated using(seller_id in(select id from public.sellers where user_id=auth.uid()));
grant select on public.categories,public.sellers,public.products to anon,authenticated;grant select on public.profiles,public.orders,public.order_items to authenticated;grant insert on public.sellers,public.products to authenticated;revoke update on public.profiles from authenticated;grant update(name,phone,avatar_url,updated_at) on public.profiles to authenticated;grant update on public.sellers,public.products to authenticated;


-- User avatar storage (Phase 1 / User Profiles)
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('avatars','avatars',true,5242880,array['image/jpeg','image/png','image/webp']::text[]) on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists tani_avatars_public_read on storage.objects;create policy tani_avatars_public_read on storage.objects for select to public using(bucket_id='avatars');
drop policy if exists tani_avatars_owner_insert on storage.objects;create policy tani_avatars_owner_insert on storage.objects for insert to authenticated with check(bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists tani_avatars_owner_update on storage.objects;create policy tani_avatars_owner_update on storage.objects for update to authenticated using(bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text) with check(bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists tani_avatars_owner_delete on storage.objects;create policy tani_avatars_owner_delete on storage.objects for delete to authenticated using(bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);


-- Phase 1 foundation: Analytics, Error Monitoring, Admin Foundation
create table if not exists public.app_events(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete set null,session_id text not null,event_name text not null check(char_length(event_name) between 2 and 80),screen text,entity_type text,entity_id uuid,metadata jsonb not null default '{}'::jsonb,app_version text,platform text not null default 'android',created_at timestamptz not null default now());
create table if not exists public.app_errors(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete set null,session_id text not null,source text not null,error_type text not null,message text,context jsonb not null default '{}'::jsonb,app_version text,platform text not null default 'android',created_at timestamptz not null default now());
alter table public.app_events enable row level security;alter table public.app_errors enable row level security;
drop policy if exists tani_app_events_anon_insert on public.app_events;create policy tani_app_events_anon_insert on public.app_events for insert to anon with check(user_id is null);
drop policy if exists tani_app_events_authenticated_insert on public.app_events;create policy tani_app_events_authenticated_insert on public.app_events for insert to authenticated with check(user_id=(select auth.uid()));
drop policy if exists tani_app_events_admin_read on public.app_events;create policy tani_app_events_admin_read on public.app_events for select to authenticated using(public.current_user_role()=any(array['admin','support']));
drop policy if exists tani_app_errors_anon_insert on public.app_errors;create policy tani_app_errors_anon_insert on public.app_errors for insert to anon with check(user_id is null);
drop policy if exists tani_app_errors_authenticated_insert on public.app_errors;create policy tani_app_errors_authenticated_insert on public.app_errors for insert to authenticated with check(user_id=(select auth.uid()));
drop policy if exists tani_app_errors_admin_read on public.app_errors;create policy tani_app_errors_admin_read on public.app_errors for select to authenticated using(public.current_user_role()=any(array['admin','support']));
grant insert on public.app_events,public.app_errors to anon,authenticated;grant select on public.app_events,public.app_errors to authenticated;
