begin;
do $$
declare sara uuid:=(select id from auth.users where email='demo.sara@tani.test' limit 1);reem uuid:=(select id from auth.users where email='demo.reem@tani.test' limit 1);amna uuid:=(select id from auth.users where email='demo.amna@tani.test' limit 1);sara_store uuid;reem_store uuid;amna_store uuid;cat_women uuid;cat_kids uuid;cat_home uuid;
begin if sara is null or reem is null or amna is null then raise exception 'Create demo Auth users first: demo.sara@tani.test, demo.reem@tani.test, demo.amna@tani.test';end if;
insert into public.categories(name)values('نساء'),('أطفال'),('بيت'),('إكسسوارات'),('هدايا')on conflict(name)do nothing;select id into cat_women from public.categories where name='نساء';select id into cat_kids from public.categories where name='أطفال';select id into cat_home from public.categories where name='بيت';
insert into public.sellers(user_id,store_name,verification_status,delivery_fee)values(sara,'سارة هاند ميد','approved',1500),(reem,'ريم كيدز','approved',2000),(amna,'لمة البيت','approved',1800)on conflict(user_id)do update set store_name=excluded.store_name,verification_status='approved',delivery_fee=excluded.delivery_fee;
select id into sara_store from public.sellers where user_id=sara;select id into reem_store from public.sellers where user_id=reem;select id into amna_store from public.sellers where user_id=amna;
insert into public.products(seller_id,category_id,name,description,price,stock,is_active)values(sara_store,cat_women,'شنطة قماش مطرزة','شنطة يدوية بتطريز سوداني بسيط ومناسبة للاستخدام اليومي.',28500,12,true),(sara_store,cat_women,'طرحة قطنية ناعمة','طرحة قطنية خفيفة بألوان متعددة.',12000,25,true),(reem_store,cat_kids,'طقم أطفال قطني','طقم مريح للأطفال للاستخدام اليومي.',22000,10,true),(reem_store,cat_kids,'لعبة تركيب تعليمية','لعبة تركيب بسيطة لتنمية التركيز والمهارات.',18500,8,true),(amna_store,cat_home,'سلة تنظيم منزلية','سلة عملية لترتيب الأدوات والأغراض الصغيرة.',16000,15,true),(amna_store,cat_home,'طقم أكواب زجاجي','طقم أكواب للاستخدام المنزلي والضيافة.',24000,9,true)on conflict do nothing;
end $$;commit;
